### ISSUE TITLE
latest update breaking lora loading

### ISSUE THREAD

**Issue by zc-huhu** [lucataco/cog-flux-dev-lora#2]
Hi,
the latest update broke inferencing with some LoRA, like: https://huggingface.co/XLabs-AI/flux-RealismLora

error message:
`Downloading LoRA weights from - HF path: XLabs-AI/flux-RealismLora
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/cog/server/worker.py", line 349, in _predict
result = predict(**payload)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
File "/src/predict.py", line 266, in predict
pipe = pipe.to("cuda")
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 435, in to
module.to(device, dtype)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1174, in to
return self._apply(convert)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
module._apply(fn)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
module._apply(fn)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
module._apply(fn)
[Previous line repeated 3 more times]
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 805, in _apply
param_applied = fn(param)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1167, in convert
raise NotImplementedError(
NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.`

**Comment by zc-huhu** [comment]
@lucataco could you help to check this issue? 
Your replicate API is broken now with previously working LoRA. 
Thanks!

**Comment by lucataco** [comment]
Hey there! Xlabs-AI trained their LoRAs differently so they never worked out of the box like other Huggingface LoRAs. Therefore, I recommend you use their [Comfy Converted LoRAs](https://huggingface.co/XLabs-AI/flux-lora-collection/tree/main)
